### ISSUE TITLE
[BUG] 4G/LTE Only Mode not available

### ISSUE THREAD

**Issue by lahceneamine** [Lethany/BeyondROM_Hub#3]
**Describe the bug**
I'm not sur if it's available on Android 12, but LTE Only Mode is not available anymore even after choosing it in Aroma (DBT CSC). 

**To Reproduce**
1. Go to Network Setting
2. Click on Network Mode for SIMx
3. See error

**Screenshots**
![Screenshot_20211205-234916_Call settings](https://user-images.githubusercontent.com/25408461/144767066-c0db3e44-f6fb-4544-a9d8-1505567a5db0.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy S21 Ultra 5G
 - Model: G998B
 - CSC : DBT

**Comment by Lethany** [comment]
@lahceneamine I think this has changed since OneUI 4.0, so I don't beleive this is a ROM issue.

**Comment by Lethany** [comment]
@lahceneamine I will have our testers confirm this however.

**Comment by Lethany** [comment]
@lahceneamine Ok, our tester has confirmed LTE mode mode is not available as of the OneUI 4.0/Android 12 upgrade.

**Comment by lahceneamine** [comment]
> @lahceneamine Ok, our tester has confirmed LTE mode mode is not available as of the OneUI 4.0/Android 12 upgrade.

That's too bad 😔

Thank you a lot for your reactivity.

I will close the issue.
