### ISSUE TITLE
[BUG] Android Car not working? 

### ISSUE THREAD

**Issue by Nexitz** [Lethany/BeyondROM_Hub#4]
**Describe the bug**
Installed Android Car manually but car is not able to activate. 

**To Reproduce**
1. Go to settings
2. Click on more functions 
3. Scroll down to Android car
4. Wont launch

**Expected behavior**
Android car connection on connecting Phone 

**Screenshots**
Add screenshots to help explain your problem.
![Screenshot_20211206-185709_Settings](https://user-images.githubusercontent.com/95647332/144897370-3e615827-93b4-438e-ae12-23744c10b168.jpg)

**Smartphone (please complete the following information):**
 - Device: Galaxy S20+ 5G
 - Model: g986b

**Comment by Lethany** [comment]
@Nexitz Have you downloaded the Android Auto app from the Google Play Store? The app is debloated by default from the System to save space.

https://play.google.com/store/apps/details?id=com.google.android.projection.gearhead

I have just installed and tested using your steps to reproduce the bug but I didn't have a problem.
